### ISSUE TITLE
Python: Smudge error: Error downloading python/packages/lab/lightning/assets/train_math_agent.png

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/agent-framework#1832]
I have a project using `uv` which pulls agent-framework dependencies using tool.uv.sources directly from the agent-framework repo.

It's currently failing because of an rrror downloading object: python/packages/lab/lightning/assets/train_math_agent.png (ab35a2b): Smudge error: Error downloading python/packages/lab/lightning/assets/train_math_agent.png

```bash
uv sync --upgrade
   Updating https://github.com/microsoft/agent-framework.git (main)                                                                                                                            
  × Failed to download and build `agent-framework-mem0 @ git+https://github.com/microsoft/agent-framework.git@main#subdirectory=python/packages/mem0`                                          
  ├─▶ Git operation failed
  ╰─▶ process didn't exit successfully: `C:\Program Files\Git\cmd\git.exe reset --hard 15433700275a2a26071016d5f824f78feb0527bb` (exit code: 128)
      --- stderr
Updating files:  86% (1526/1795)/1795)
Updating files:  91% (1634/1795)
Updating files:  97% (1724/1795)
Updating files: 100% (1795/1795), done.
      Downloading python/packages/lab/lightning/assets/train_math_agent.png (153 KB)
      Error downloading object: python/packages/lab/lightning/assets/train_math_agent.png (ab35a2b): Smudge error: Error downloading python/packages/lab/lightning/assets/train_math_agent.png
      (ab35a2bd18794a32b76437671ae7e5749992c8aa781030b51eca2e56acfb362d): error transferring "ab35a2bd18794a32b76437671ae7e5749992c8aa781030b51eca2e56acfb362d": [0] remote missing object
      ab35a2bd18794a32b76437671ae7e5749992c8aa781030b51eca2e56acfb362d

      Errors logged to 'C:\Users\markwallace\AppData\Local\uv\cache\git-v0\checkouts\4b1e1d86a9ff4f1a\15433700\.git\lfs\logs\20251031T112415.8377256.log'.
      Use `git lfs logs last` to view the log.
      error: external filter 'git-lfs filter-process' failed
      fatal: python/packages/lab/lightning/assets/train_math_agent.png: smudge filter lfs failed
```

**Comment by markwallace-microsoft** [comment]
The issue was resolved by temporarily skipping Git LFS file downloads using:

`$env:GIT_LFS_SKIP_SMUDGE = "1"; uv sync --upgrade`

**Comment by ekzhu** [comment]
Regular git clone downloads the PNG file successfully. But if you use `uv` it actually uses your local cached copy in `~/.cache/uv/` and for some reason (may be a bug in uv) it always fails to download this specific file from GitHub LFS storage. This specific file had some issue before that it was not properly uploaded when first checked in, but it was later fixed in a separate commit.

Let me see if I can do a force upload of all LFS objects again.

**Comment by ekzhu** [comment]
The issue still persists after I ran `git lfs push origin --object-id ab35a2bd18794a32b76437671ae7e5749992c8aa781030b51eca2e56acfb362d` for this particular file. 

Created an issue with uv: astral-sh/uv#16539

**Comment by pamelafox** [comment]
We had this reported on our repo as well:
https://github.com/Azure-Samples/python-agentframework-demos/issues/16#issuecomment-3960406051

**Comment by moonbox3** [comment]
Bug fixed via uv.
